version: '3'
services:
    app:
        restart: always
        build: ./app
        expose:
            - "8080"
        ports:
            - "8080:8080"
        # in order to use unicorn we need to change the command
        # -w referes to number of wrokers
        # -b specifies port
        command: '/usr/local/bin/gunicorn -b :8080 app:app'
        depends_on:
            - db
            # - nginx
    nginx:
        restart: always
        image: nginx
        expose:
            - "8080"
        ports:
            - "80:80"
        volumes:
            - ./nginx/flask_app.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - app
    data:
        restart: always
        image: postgres
        volumes: 
            - /var/lib/postgresql
        command: "true"
    db:
        restart: always
        image: postgres
        volumes:
            - /var/lib/postgresql
        depends_on:
            - data
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=postgres
